import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { compileRobloxProject } from '../my-ui/src/features/project-compiler.ts'
import { PreviewFeature } from '../my-ui/src/features/preview-feature.ts'
import { ShopFeature } from '../my-ui/src/features/shop-feature.ts'
import { SettingsFeature } from '../my-ui/src/features/settings-feature.ts'
import { exportCompiledProjectToRbxmx } from '../my-ui/src/sync/rbxmx.ts'

const workspace = new URL('../', import.meta.url)
const outputRoot = new URL('dist/roblox/', workspace)

export async function buildRobloxProject({ clean = true } = {}) {
  const report = { version: 1, status: 'passed', errors: [], warnings: [], files: [] }
  let project
  const generated = new Map()
  try {
    project = compileRobloxProject([PreviewFeature, ShopFeature, SettingsFeature])
    validateProject(project)
    generated.set('UI/CompiledProject.rbxmx', exportCompiledProjectToRbxmx(project))
    for (const service of [...project.Nerve.Services].sort()) generated.set(`Services/${service}.luau`, await readCanonicalOrGenerate(`../roblox/nerve/${service}.luau`, generateService(service, project.Network[service] ?? {})))
    for (const controller of [...project.Nerve.Controllers].sort()) generated.set(`Controllers/${controller}.luau`, await readCanonicalOrGenerate(`../roblox/nerve/${controller}.luau`, generateController(controller, project)))
    for (const [path, source] of Object.entries(project.SharedModules).sort(([left], [right]) => left.localeCompare(right))) generated.set(`Shared/${normalizeRelativePath(path)}`, source.endsWith('\n') ? source : `${source}\n`)
    generated.set('Network/manifest.json', stableJson({ version: 1, services: project.Network }))
    generated.set('project.json', stableJson(serializableProject(project)))
    report.warnings.push(...(project.Bindings.length ? [`Validated ${project.Bindings.length} reactive binding path(s).`] : []))
    report.files = [...generated.keys()].sort()
  } catch (error) {
    report.status = 'failed'
    report.errors.push(error instanceof Error ? error.message : String(error))
  }
  if (clean && report.status === 'passed') await rm(outputRoot, { recursive: true, force: true })
  await mkdir(outputRoot, { recursive: true })
  if (report.status === 'passed') for (const [relativePath, source] of [...generated].sort(([left], [right]) => left.localeCompare(right))) { const target = new URL(relativePath, outputRoot); await mkdir(new URL('.', target), { recursive: true }); await writeFile(target, source) }
  await writeFile(new URL('build-report.json', outputRoot), stableJson(report))
  if (report.status === 'failed') throw new Error(report.errors.join('\n'))
  return report
}

async function readCanonicalOrGenerate(relativePath, fallback) {
  try {
    return await readFile(new URL(relativePath, import.meta.url), 'utf8')
  } catch (error) {
    if (error?.code !== 'ENOENT') throw error
    return fallback
  }
}

function validateProject(project) {
  for (const name of [...project.Nerve.Services, ...project.Nerve.Controllers]) if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) throw new Error(`Invalid Roblox identifier: ${name}`)
  for (const path of Object.keys(project.SharedModules)) if (path.includes('..') || path.startsWith('/') || path.includes('\\')) throw new Error(`Invalid shared module path: ${path}`)
  for (const [service, endpoints] of Object.entries(project.Network)) for (const [endpoint, definition] of Object.entries(endpoints)) { if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(service) || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(endpoint)) throw new Error(`Invalid network identifier: ${service}.${endpoint}`); if (definition.kind === 'method' && (!definition.request || !definition.response)) throw new Error(`Incomplete method contract: ${service}.${endpoint}`) }
}

function generateService(name, endpoints) {
  const signals = Object.entries(endpoints).filter(([, endpoint]) => endpoint.kind === 'signal')
  const methods = Object.entries(endpoints).filter(([, endpoint]) => endpoint.kind === 'method')
  const lines = ['--!strict', '', '-- Generated by build:roblox. Do not edit by hand.', 'local ReplicatedStorage = game:GetService("ReplicatedStorage")', 'local Nerve = require(ReplicatedStorage.Nerve)', 'local S = Nerve.Schema', '', `local ${name} = Nerve.CreateService({`, `\tName = ${quote(name)},`, '\tClient = {']
  for (const [endpoint, definition] of signals) lines.push(`\t\t${endpoint} = Nerve.Signal(${schemaExpression(definition.arguments)}${signalOptions(definition)}),`)
  lines.push('\t},', '\tNetwork = {')
  for (const [endpoint, definition] of methods) lines.push(`\t\t${endpoint} = Nerve.Method({ Request = ${schemaExpression(definition.request)}, Response = ${schemaExpression(definition.response)}${methodOptions(definition)} }),`)
  lines.push('\t},', '})', '')
  for (const [endpoint, definition] of methods) { const arity = definition.request.kind === 'tuple' ? definition.request.items.length : 1; const args = Array.from({ length: arity }, (_, index) => `value${index + 1}`).join(', '); lines.push(`function ${name}.Client:${endpoint}(_player: Player${args ? `, ${args}` : ''})`, '\t-- Implement the authoritative server behavior here.', '\treturn nil', 'end', '') }
  lines.push(`return ${name}`, '')
  return lines.join('\n')
}

function generateController(name, project) { const lines = ['--!strict', '', '-- Generated by build:roblox. Do not edit by hand.', 'local ReplicatedStorage = game:GetService("ReplicatedStorage")', 'local Nerve = require(ReplicatedStorage.Nerve)', '', `local ${name} = Nerve.CreateController({`, `\tName = ${quote(name)},`, '})', '', `function ${name}:NerveInit()`]; for (const service of project.Nerve.Services) lines.push(`\tlocal ${service} = Nerve.GetService(${quote(service)})`, `\tself.${service} = ${service}`); lines.push('end', '', `function ${name}:NerveStart()`, 'end', '', `return ${name}`, ''); return lines.join('\n') }
function methodOptions(definition) { const options = []; if (definition.timeout !== undefined) options.push(`, Timeout = ${definition.timeout}`); if (definition.rateLimit === false) options.push(', RateLimit = false'); return options.join('') }
function signalOptions(definition) { const options = []; if (definition.direction) options.push(`, { Direction = ${quote(definition.direction)} }`); return options.join('') }
function schemaExpression(schema) { if (schema.kind === 'optional' || schema.kind === 'array') return `S.${schema.kind[0].toUpperCase()}${schema.kind.slice(1)}(${schemaExpression(schema.value)})`; if (schema.kind === 'map') return `S.Map(${schemaExpression(schema.key)}, ${schemaExpression(schema.value)})`; if (schema.kind === 'struct') return `S.Struct({ ${Object.entries(schema.fields).sort(([left], [right]) => left.localeCompare(right)).map(([name, value]) => `${name} = ${schemaExpression(value)}`).join(', ')} })`; if (schema.kind === 'tuple') return `S.Tuple({ ${schema.items.map(schemaExpression).join(', ')} })`; return `S.${({ bool: 'Boolean', string: 'String', float64: 'Float64', int32: 'Int32' }[schema.kind] ?? capitalize(schema.kind))}` }
function capitalize(value) { return value[0].toUpperCase() + value.slice(1) }
function quote(value) { return JSON.stringify(value) }
function normalizeRelativePath(value) { const normalized = value.replaceAll('\\', '/').replace(/^\/+/, '').replace(/^shared\//i, ''); return normalized.endsWith('.luau') ? normalized : `${normalized}.luau` }
function serializableProject(project) { return { Features: project.Features, Tree: project.Tree, State: project.State, Bindings: project.Bindings, Actions: Object.keys(project.Actions).sort(), Effects: project.Effects, Scenarios: project.Scenarios.map(({ configure, steps, triggers, ...scenario }) => ({ ...scenario, StepLabels: steps.map((step) => ({ afterMs: step.afterMs, label: step.label })), TriggerIds: triggers?.map((trigger) => trigger.id) })), Nerve: project.Nerve, Network: project.Network, SharedModules: project.SharedModules } }
function stableJson(value) { return `${JSON.stringify(value, (key, nested) => nested && typeof nested === 'object' && !Array.isArray(nested) ? Object.fromEntries(Object.entries(nested).sort(([left], [right]) => left.localeCompare(right))) : nested, 2)}\n` }

if (import.meta.url === pathToFileURL(resolve(process.argv[1])).href) { const report = await buildRobloxProject(); console.log(`Roblox build ${report.status}: ${report.files.length} files`); }
